### ISSUE TITLE
I user PowerColor Rx 5700 with glitch

### ISSUE THREAD

**Issue by Goooler** [portrayer/Clover-Ryzen-MSI-B450I#4]
My CPU and motherboard are same as yours, but GPU is [PowerColor Rx 5700 ](https://www.powercolor.com/product?id=1562142290), I prepared a bootable macOS USB and replace the EFI of you then boot up, the glitch happened, can you help me ?

**Comment by Goooler** [comment]
![IMG_20191125_000720](https://user-images.githubusercontent.com/10363352/69497653-8600ff00-0f1a-11ea-9ee0-b3d4e87930f9.jpg)

**Comment by portrayer** [comment]
I think this is a bug of 10.15.1, you may need install 10.15 first, then upgrade to 10.15.1

**Comment by Goooler** [comment]
But rx 5700 was supported from 10.15.1, how can I drive it from 10.15 ?
Maybe I should inject EDID or change something in config.plst ?

**Comment by Goooler** [comment]
And I tried to boot up with DP but black screen, switch to HDMI is ok but glitchs like the picture above

**Comment by portrayer** [comment]
you still can install 10.15 without graphics acceleration, then upgrade to 10.15.1.
during upgrade you'll also get broken display, don't worry, 5700 will be ready when upgrade finished.

btw, 10.15.2 beta has fixed this problem, so you may like to wait 10.15.2 and vanilla patch release.

**Comment by Goooler** [comment]
Thx.
Did you mean you also had the glitch issue when you  install ?

**Comment by Goooler** [comment]
老哥是也在中国吗，看你资料才发现，尬聊了半天

**Comment by portrayer** [comment]
哈哈，是的，我的三脚猫英文打的好费劲

**Comment by Goooler** [comment]
老哥，那你之前也遇到过花屏吗？也是从10.15升级的还是怎么弄的？

**Comment by portrayer** [comment]
没有，我之前用的480，升级到10.15.1才换5700

**Comment by Goooler** [comment]
老哥，我俺你说的先装10.15再升级到 10.15.1果然不花屏了，有个小问题就是只能用 hdmi 输出，接 dp 是黑屏，你看有啥解决办法吗，再次感谢

**Comment by portrayer** [comment]
这个我没遇到过，whatevergreen升级到最新了吗？启动参数有agdpmod=pikera吗？

**Comment by Goooler** [comment]
用的就是你这版，whateverGreen 是最新版，启动参数也是有的，别的完美，唯有 dp 开机后黑屏，现在用 hdmi ，不过问题不大
